### ISSUE TITLE
Ability to add own Faces

### ISSUE THREAD

**Issue by Seklfreak** [tangerinetulip/somina#2]
Somi and Mina are nice but there are more

**Comment by tangerinetulip** [comment]
Fixed with commit c6150475c58c1c149d3e74e67a028de6b47359f7. You still have to manually add the subject person(s) in follow.toml though. Also I still have to add sample TOML files, which will be done next commit.

**Comment by tangerinetulip** [comment]
Configuration TOML files generated as of commit d8743939a6553fc93ecd047da988a18584ad40c4.
